# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mail' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for Mail
  pod 'GoogleSignIn'
  pod 'GoogleSignInSwiftSupport'

  project 'Mail.xcodeproj'

  target 'MailTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MailUITests' do
    # Pods for testing
  end

end
